### ISSUE TITLE
Tab key can't indent after using ac-clang

### ISSUE THREAD

**Issue by zijianyue** [yaruopooner/ac-clang#5]
Advice:Can you improve the manual trigger function just like ac-trigger-key-command in auto-complete, which trigger completion only when needed.

**Comment by yaruopooner** [comment]
Hi, yes I know it.
It's seen as the same function seemingly, but it's different in internal implementation.

ac-trigger-key-command is executed auto-complete-1 at internal.
ac-clang-async-autocomplete-manualtrigger is executed IPC at internal.

**Comment by yaruopooner** [comment]
I think about the method to reflect "TAB".
I did not notice this problem.
Because I used "C-i" for an indent.

I want you to avoid by the following way for now.

;; disable
(setq ac-clang-async-autocomplete-manualtrigger-key nil)
;; other key
(setq ac-clang-async-autocomplete-manualtrigger-key "M-:")

**Comment by zijianyue** [comment]
Ok ,thank you very much for help. I set it to other key now

**Comment by yaruopooner** [comment]
sorry, word spell miss.

;;NG
ac-clang-async-autocomplete-manualtrigger-key
;;OK
ac-clang-async-autocompletion-manualtrigger-key
